mozilla-ai/any-agent

src/any_agent/telemetry/langchain_telemetry.py, src/any_agent/telemetry/llama_index_telemetry.py, src/any_agent/telemetry/openai_telemetry.py, src/any_agent/telemetry/smolagents_telemetry.py, src/any_agent/telemetry/telemetry.py
extract_interaction returns a tuple now, update typing as well as the telemetry extraction
=> bugfix for span extraction

.codespellrc, docs/evaluation.md, mkdocs.yml, pyproject.toml, src/any_agent/evaluation/evaluate.py, src/any_agent/evaluation/evaluators/CheckpointEvaluator.py, src/any_agent/evaluation/evaluators/HypothesisEvaluator.py, src/any_agent/evaluation/evaluators/LLMEvaluator.py, src/any_agent/evaluation/evaluators/QuestionAnsweringSquadEvaluator.py, src/any_agent/evaluation/evaluators/__init__.py, src/any_agent/evaluation/evaluators/schemas.py, src/any_agent/evaluation/logging.py, src/any_agent/evaluation/results_saver.py, src/any_agent/evaluation/test_case.py, src/any_agent/telemetry/langchain_telemetry.py
@stefanfrench  Added you if you can read through the doc page
=> Evaluation Codebase Comes to Any-Agent

README.md
I will wait for approval before merging this one, I could go either way but it seemed like it might be nice to directly say "we know we have more frameworks to support and we welcome help making it happen"
=> More direct calls for contribution

src/any_agent/frameworks/any_agent.py, src/any_agent/frameworks/google.py, src/any_agent/frameworks/langchain.py, src/any_agent/frameworks/llama_index.py, src/any_agent/frameworks/openai.py, src/any_agent/frameworks/smolagents.py, src/any_agent/tools/mcp.py, src/any_agent/tools/wrappers.py, tests/integration/test_load_and_run_agent.py, tests/integration/test_mcp.py, tests/unit/frameworks/test_google.py, tests/unit/frameworks/test_langchain.py, tests/unit/frameworks/test_llama_index.py, tests/unit/frameworks/test_openai.py, tests/unit/frameworks/test_smolagents.py, tests/unit/tools/test_unit_mcp.py
I know that I  have a latent issue here where i use a global `_mcps` variable to keep the MCP servers alive for the lifetime of the python process. I need to fix that, tracked https://github.com/mozilla-ai/any-agent/issues/64 
This PR also fixes Langchain so that Langchain will work with MCP servers now 🚀
=> MCP becomes more async

src/any_agent/evaluation/evaluators/CheckpointEvaluator.py, src/any_agent/evaluation/results_saver.py, src/any_agent/evaluation/test_case.py, src/any_agent/frameworks/any_agent.py, src/any_agent/frameworks/google.py, src/any_agent/frameworks/langchain.py, src/any_agent/frameworks/llama_index.py, src/any_agent/frameworks/openai.py, src/any_agent/frameworks/smolagents.py, src/any_agent/tools/mcp.py, tests/unit/frameworks/test_google.py, tests/unit/frameworks/test_langchain.py, tests/unit/frameworks/test_llama_index.py, tests/unit/frameworks/test_openai.py, tests/unit/frameworks/test_smolagents.py, tests/unit/tools/test_unit_mcp.py
I didn't realize that async tests get skipped unless you put a plugin into place. This re-arranges the load_agent code to be a part of the create function instead of being dynamically loaded at agent run time
=> Tests are sync

docs/tools.md, src/any_agent/config.py, src/any_agent/tools/wrappers.py, tests/integration/test_import_and_wrap_tools.py
Add `tests/integration/test_import_and_wrap_tools`.
=> feat(tools): Support passing callable.

README.md
Update quickstart to show tracing.
Split into single and multi-agent examples.
Add more links to docs.
=> Minor Updates to README.

tests/conftest.py
https://github.com/mozilla-ai/any-agent/actions/runs/14469560059/job/40579792875?pr=85
=> tests: Add autouse fixture `disable_rich_console`.

docs/api.md, docs/tools.md, pyproject.toml, src/any_agent/config.py, src/any_agent/tools/mcp.py, src/any_agent/tools/wrappers.py, tests/conftest.py, tests/integration/test_load_and_run_agent.py, tests/integration/test_load_and_run_multi_agent.py, tests/unit/tools/test_unit_mcp.py
I also cleaned up the MCP implementations by using ExitStacks so that the aexit's should get called when the stack exits.
=> OpenAI and Smolagents SSE support

.pre-commit-config.yaml, src/any_agent/__init__.py, src/any_agent/evaluation/evaluators/__init__.py, src/any_agent/frameworks/langchain.py, src/any_agent/frameworks/llama_index.py, src/any_agent/tools/__init__.py
- Adjust argument formatting for clarity.
- Update ruff hook version to v0.11.6.
- Upgrade codespell hook version to v2.4.1.
=> Add pre-commit-autoupdate hook and lint with latest version of ruff

tests/integration/test_mcp.py
`search_web` was causing random failures.
---
Successful run:
https://github.com/mozilla-ai/any-agent/actions/runs/14597684872
=> tests(mcp): Use dumb tool instead of `search_web`.

src/any_agent/tracing.py, tests/integration/test_load_and_run_agent.py
Update `test_load_and_run_agent` to use tracing.
=> fix(tracing): Include framework name in output file.

docs/index.md, src/any_agent/frameworks/any_agent.py
=> feat(any_agent): Expose `create_async`.

README.md, docs/index.md, tests/docs/test_all.py
=> fix(docs): Use `python` in code blocks to enusre `mktestdocs` runs.

src/any_agent/frameworks/tinyagent.py, src/any_agent/tools/mcp/frameworks/tinyagent.py
Because the MCP callable is getting created with *args and **kwargs, the information about what parameters were required was being lost.
=> MCP tools were missing schema

pyproject.toml
Thanks for the find, @HareeshBahuleyan !
=> Upgrade google-adk min version

pyproject.toml
Drop unnecessary `litellm` and `mcp` extra deps (move them to required deps).
=> chore(deps): Bump `agno>=1.4.4`.

src/any_agent/frameworks/any_agent.py, src/any_agent/tracing/processors/base.py, src/any_agent/tracing/trace.py, tests/integration/test_load_and_run_agent.py, tests/integration/test_load_and_run_multi_agent.py, tests/unit/tracing/test_unit_processors.py
The new test added in this PR will expose the part of the code in main that is currently broken.
=> Tracing support helper function and integration test that exposes bug.

src/any_agent/frameworks/agno.py, src/any_agent/frameworks/any_agent.py, src/any_agent/frameworks/google.py, src/any_agent/frameworks/langchain.py, src/any_agent/frameworks/llama_index.py, src/any_agent/frameworks/openai.py, src/any_agent/frameworks/smolagents.py, src/any_agent/frameworks/tinyagent.py, tests/integration/test_load_and_run_agent.py
This doesn't have to be the final design but at least for the moment it solves the problem of `agent.run`s appending on top of each other
=> Reset tracing at the beginning of each run

docs/frameworks/google_adk.md, docs/frameworks/openai.md, src/any_agent/config.py, src/any_agent/frameworks/google.py, src/any_agent/frameworks/openai.py, tests/unit/frameworks/test_google.py, tests/unit/frameworks/test_openai.py
Expect it to be passed in `agent_args` instead.
=> refactor: Drop `handoff` from `AgentConfig`.

pyproject.toml
Add a timeout so that a hanging test won't hang the process.
=> Add pytest timeout

tests/unit/frameworks/test_tinyagent.py
I realized that I forgot to add a unit test for tiny_agent.
=> Add unit test for tinyagent

.github/workflows/docs.yaml, src/any_agent/frameworks/agno.py, src/any_agent/frameworks/langchain.py, src/any_agent/frameworks/llama_index.py, src/any_agent/frameworks/tinyagent.py, tests/integration/test_load_and_run_agent.py, tests/integration/test_load_and_run_multi_agent.py, tests/unit/frameworks/test_langchain.py, tests/unit/frameworks/test_llama_index.py
I noticed this because for HF Spaces I need to pass in a custom header for billing purposes, and it wasn't making it to several of the frameworks 😬
=> [Bug] Completion Kwargs not always getting passed correctly

tests/conftest.py, tests/unit/frameworks/test_any_agent.py, tests/unit/serving/test_agent_card.py
Pass frequency_penalty and temperature as model_args and verify that they get passed to LiteLLM.
=> Unit Testing for passing of model args

tests/integration/test_load_and_run_multi_agent.py
See issue #256 for details and to track fix and removal of this skipping.
=> Disable broken multi-agent trace checks 

pyproject.toml, tests/integration/test_load_and_run_agent.py
To keep our integration tests as small as possible, I added an "evaluation" stage to our existing agent run.
=> Add Evaluation to Integration Test

src/any_agent/tools/web_browsing.py, tests/unit/tools/test_unit_web_browsing.py
=> Fix typo tavily

src/any_agent/evaluation/agent.py, src/any_agent/evaluation/evaluate.py, src/any_agent/evaluation/evaluators.py, tests/integration/test_load_and_run_agent.py, tests/unit/evaluation/test_evaluate.py
- Introduced a new `AgentTooling` class to streamline access to agent trace outputs, including final output, token usage, step count, and evidence from spans.
- Implemented a `get_agent` function to create an `AnyAgent` instance with the new tooling, enhancing the evaluation process.
- Updated `evaluate.py` to use the renamed `evaluate_checkpoints` function for clarity and consistency.
This update improves the overall evaluation framework, making it easier to gather and analyze agent performance data!
=> Add evaluation agent for streamiined evaluation capabilities

pyproject.toml
Bug prevents debugpy from attaching
=> Pin frozenlist

pyproject.toml, src/any_agent/tools/mcp/frameworks/google.py
mypy was trying to tell use something but we ignored it.
=> fix(mcp/google): Update imports.

src/any_agent/frameworks/llama_index.py
Sorry for the premature merge on the other one before you reviewed.
=> Only make extra llm call if pydantic validation fails

tests/integration/a2a/test_a2a_serve.py, tests/integration/a2a/test_a2a_tool.py, tests/integration/a2a/test_a2a_tool_multiturn.py, tests/integration/helpers.py, tests/integration/mcp/test_mcp_serve.py, tests/integration/test_agent.py, tests/integration/test_error_handling.py, tests/integration/test_thread_safe.py, tests/integration/tracing/test_no_instrument.py
This is to clean up so that my Mistral PR is a little smaller.
=> Consolidate the model id into variables

.github/workflows/lint.yaml
Cache both pre-commit (uv env/python deps) and mypy (cached mypy command artifacts)
=> Cache MyPy and Pre-Commit for faster lint

pyproject.toml, src/any_agent/callbacks/span_generation/smolagents.py, src/any_agent/tools/mcp/frameworks/smolagents.py, tests/unit/tools/mcp/test_unit_smolagents_mcp.py
Integration tests: https://github.com/mozilla-ai/any-agent/actions/runs/16203274885
=> feat: smolagents support timeout parameter

tests/integration/a2a/test_push_notification.py
=> Update push assertions according to a2a v0.2.12

pyproject.toml
=> chore(deps): Remove `fire` dependency from pyproject.toml

.github/workflows/tests-cookbook.yaml, .github/workflows/tests-docs.yaml, .github/workflows/tests-integration.yaml, .github/workflows/tests-unit.yaml, pyproject.toml
Set global `branch` option instead of flags.
Exclude `vendor`.
=> chore: Update codecov config.

src/any_agent/serving/a2a/agent_executor.py, tests/integration/a2a/conftest.py, tests/integration/a2a/test_a2a_tool_multiturn.py, tests/integration/a2a/test_push_notification.py, tests/unit/serving/test_agent_card.py
Fix tests and typechecks due to breaking changes in A2A 0.3.0.
=> Fix typecheck for a2a 0.3.0

.github/workflows/tests-integration.yaml, tests/integration/frameworks/test_agent.py
https://github.com/mozilla-ai/any-agent/actions/runs/16726796358/job/47344465955
=> tests: Enable xai integration tests.

src/any_agent/frameworks/tinyagent.py
Focus more on tool calling and `final_answer` behavior.
The idea is to help smaller language models.
=> feat(tiny_agent): Update instructions.

src/any_agent/serving/a2a/agent_card.py, src/any_agent/serving/a2a/agent_executor.py, src/any_agent/serving/a2a/config_a2a.py, src/any_agent/serving/a2a/server_a2a.py, tests/integration/a2a/conftest.py, tests/integration/a2a/test_a2a_serve.py, tests/integration/conftest.py
Cleanup on top of https://github.com/mozilla-ai/any-agent/pull/685.
=> feat(a2a): Add streaming support.

docs/agents/callbacks.md
=> Updated Callbacks Docs

.github/workflows/lint.yaml, .github/workflows/tests-integration.yaml, pyproject.toml, scripts/run-mypy.sh, src/any_agent/frameworks/tinyagent.py, src/any_agent/tools/composio.py, tests/integration/tools/test_composio.py
Generic provider that can be used with any of the frameworks.
=> feat: Support `composio` via custom `CallableProvider`.

.github/workflows/tests-docs.yaml, docs/agents/tools.md, tests/docs/test_all.py
- Group Composio and Agent as Tools under `Callable`.
=> docs(tools): Add `Composio` section.

src/any_agent/utils/cast.py, tests/unit/utils/test_cast.py
Every time I trust Claude too much I regret it 😅. There was nonsensical boolean casting behavior that I failed to catch in my review the first time.
=> fix: proper boolean safe casting and unit test consolidation
