- pyproject.toml
- src/any_agent/frameworks/llama_index.py
- tests/unit/frameworks/test_llama_index.py
Helps standardizing the default `model_id` behavior.
> feat(llama_index): Use `LiteLLM` as default model class.

- docs/frameworks.md
- pyproject.toml
- src/any_agent/config.py
- src/any_agent/frameworks/__init__.py
- src/any_agent/frameworks/any_agent.py
- src/any_agent/frameworks/google.py
- src/any_agent/tools/wrappers.py
- tests/integration/test_load_and_run_agent.py
- tests/integration/test_load_and_run_multi_agent.py
- tests/unit/frameworks/test_google.py
- tests/unit/tools/test_unit_wrappers.py
- Use `LiteLlm` as default model class.
- Implement managed_agents using "AgentTool" and `sub_agents` (when handoff=True).
> feat: Add support for Google Agent Development Kit (ADK)

- src/any_agent/frameworks/any_agent.py
- src/any_agent/frameworks/google.py
- src/any_agent/frameworks/langchain.py
- src/any_agent/frameworks/llama_index.py
- src/any_agent/frameworks/openai.py
- src/any_agent/frameworks/smolagents.py
In prod use cases, async appears to be the popular choice. So, lets begin building for the async world. Each agent implementation uses async, but there is an entry `sync` option in the any-agent class that calls asyncio.run to keep sync an option.
> Make Agent.run use async under the hood

- .github/workflows/tests.yaml
- src/any_agent/frameworks/google.py
- src/any_agent/frameworks/langchain.py
- src/any_agent/frameworks/llama_index.py
- src/any_agent/frameworks/openai.py
- src/any_agent/frameworks/smolagents.py
- tests/conftest.py
- tests/integration/test_load_and_run_agent.py
- tests/integration/test_load_and_run_multi_agent.py
- tests/integration/test_mcp.py
- Use `gemini/gemini-2.0-flash` via LiteLLM for frameworks that support it.
- Add `setup_tracing` for frameworks that support it.
- Use `ANY_AGENT_INTEGRATION_TESTS` env var. Closes https://github.com/mozilla-ai/any-agent/issues/34
- Run integration tests in Github Actions workflow
> Improvements to integration tests

- docs/api.md
- docs/tracing.md
- src/any_agent/config.py
- src/any_agent/telemetry/langchain_telemetry.py
- src/any_agent/tracing.py
- tests/integration/test_telemetry_tracing.py
- tests/unit/test_unit_tracing.py
Decided to disable `CHAIN` and `AGENT` by default. They were too noisy in some frameworks (`langchain`, `llama_index`)
> 74 allow to configure tracing console output

- .github/workflows/tests.yaml
This allows to run those tests manually on a PR (i.e. after it has been approved)
> tests: Allow to run integration tests via `workflow_dispatch`.

- README.md
- docs/evaluation.md
- docs/tracing.md
- src/any_agent/__init__.py
- src/any_agent/config.py
- src/any_agent/frameworks/agno.py
- src/any_agent/frameworks/any_agent.py
- src/any_agent/frameworks/google.py
- src/any_agent/frameworks/langchain.py
- src/any_agent/frameworks/llama_index.py
- src/any_agent/frameworks/openai.py
- src/any_agent/frameworks/smolagents.py
- src/any_agent/tracing.py
- tests/integration/test_load_and_run_agent.py
- tests/integration/test_load_and_run_multi_agent.py
- tests/unit/frameworks/test_anyagent.py
- tests/unit/test_unit_tracing.py
In order to simplify the process for users, refactor setup_tracing to be a part of creating an agent, so that the user doesn't need to call setup_tracing, they can pass a TracingConfig object into the create function, and then the trace path will be stored as a member variable of the AnyAgent object.
> Tracing as a setting when creating the Agent

- src/any_agent/tracing.py
Sometimes the interaction is an empty dict, so there's nothing to log
> If the interaction is empty, don't log the bars

- src/any_agent/config.py
- src/any_agent/tools/mcp/frameworks/langchain.py
Langchain was the only framework where the bug was in our code. For the rest of them, we need to pipe our config setting into their frameworks once the bug fix propogates to their codebase
> fix: langchain mcp hang

- pyproject.toml
- pytest.ini
- src/any_agent/tools/mcp/frameworks/google.py
- src/any_agent/tools/mcp/frameworks/langchain.py
- src/any_agent/tools/mcp/frameworks/openai.py
- src/any_agent/tools/mcp/frameworks/smolagents.py
- src/any_agent/tools/mcp/mcp_server.py
- tests/conftest.py
- tests/unit/tools/test_unit_mcp.py
Most of the work here went into the unit testing. I figured out how to mock the underlying part of the MCP lib that everyone uses.
I only mocked and test the stdio functionality because SSE isn't yet supported across frameworks. For instance, Agno just added support for it in a commit from 5 hours ago 😆  https://github.com/agno-agi/agno/pull/2892/files 
Llama Index doesn't yet support SSE but I think it's on their roadmap.
> Filter MCP Tools and write a unit test to check it

- src/any_agent/config.py
- src/any_agent/tracing.py
- tests/integration/test_telemetry_tracing.py
Can be disabled with `TracingConfig(cost_info=False)`.
Example output:
> feat(tracing): Add `cost_info` option.

- src/any_agent/config.py
- src/any_agent/frameworks/any_agent.py
- src/any_agent/tracing.py
- tests/unit/frameworks/test_any_agent.py
- tests/unit/test_unit_tracing.py
This is the beginnings of the changes to support
https://github.com/mozilla-ai/any-agent/issues/92 
and 
https://github.com/mozilla-ai/any-agent/issues/160
By storing the trace object as a member of the agent, we'll be able to access the trace information (and maybe the cost information from the traces, not sure yet) in a clean way. The existing implementation is storing the trace_filepath as a parameter of AnyAgent separate from the tracing functions, which imo is making our lives a little more complicated than it needs to be.
> Tracing as a class

- src/any_agent/__init__.py
- src/any_agent/frameworks/agno.py
- src/any_agent/frameworks/any_agent.py
- src/any_agent/frameworks/google.py
- src/any_agent/frameworks/langchain.py
- src/any_agent/frameworks/llama_index.py
- src/any_agent/frameworks/openai.py
- src/any_agent/frameworks/smolagents.py
- src/any_agent/frameworks/tinyagent.py
- tests/integration/test_load_and_run_agent.py
- tests/integration/test_load_and_run_multi_agent.py
- tests/integration/test_mcp.py
- tests/unit/frameworks/test_smolagents.py
Now when the Agent.run returns, you always can get a reasonable answer at result.final_output, and some tracing when available at `raw_responses`.
We'll add some more keys to this output object soon, like execution time, cost, etc. 
We also will improve on raw_responses by populating it with the normalized trace object. But this PR should be nice enough to get us started.
> Consistent return no matter which agent framework

- docs/instructions.md
- src/any_agent/config.py
- src/any_agent/frameworks/agno.py
- src/any_agent/frameworks/google.py
- src/any_agent/frameworks/langchain.py
- src/any_agent/frameworks/llama_index.py
- src/any_agent/frameworks/openai.py
- src/any_agent/frameworks/smolagents.py
- tests/integration/test_load_and_run_agent.py
- tests/integration/test_load_and_run_multi_agent.py
- tests/unit/frameworks/test_agno.py
- tests/unit/frameworks/test_google.py
- tests/unit/frameworks/test_langchain.py
- tests/unit/frameworks/test_llama_index.py
- tests/unit/frameworks/test_openai.py
- tests/unit/frameworks/test_smolagents.py
Only add `agent_type` in frameworks where multiple classes are provided. Drop string imports.
- smolagents: Use ToolCallingAgent as default
> feat: Support `agent_type` and `model_type` in every framework.

- tests/unit/frameworks/test_langchain.py
This is to fix
tests/unit/frameworks/test_langchain.py::test_run_langchain_agent_custom_args
/Users/nbrake/scm/any-agent/src/any_agent/frameworks/langchain.py:138: RuntimeWarning: coroutine 'AsyncMockMixin._execute_mock_call' was never awaited
if not result.get("messages"):
Enable tracemalloc to get traceback where the object was allocated.
See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
> Fix warning log in test_langchain

- docs/evaluation.md
- docs/tracing.md
- src/any_agent/config.py
- src/any_agent/tracing/exporter.py
- src/any_agent/tracing/trace.py
- tests/docs/test_all.py
- tests/integration/test_load_and_run_agent.py
- tests/integration/test_load_and_run_multi_agent.py
- tests/unit/tracing/test_unit_exporter.py
Per our discussion, it is no longer the responsibility of any-agent to manage and save output files for an AgentTrace. the developer who calls `agent.run()` is now responsible to save it to a file if they want it.
> Saving AgentTrace to a file is now the user/developers responsibility.

- src/any_agent/tools/mcp/frameworks/agno.py
- tests/unit/tools/mcp/conftest.py
- tests/unit/tools/mcp/test_unit_agno_mcp.py
Agno expects the argument to be None https://github.com/agno-agi/agno/blob/1bea45ea0f8801113ddd52c4626a616ef7043c5b/libs/agno/agno/tools/mcp.py#L198 otherwise no available tools are returned.
> fix(AgnoMCPConnection): Pass `include_tools=None` if no tools.

- .gitignore
- pyproject.toml
Using `extend-select = ["ALL"]` in the `pyproject.toml` means the ruff formatter evaluates all rules that aren't ignored. 
This PR adds two of them to the ignore list:
* D203: Blank line required between class declaration and docstring
* D213: Docstring cannot start on same line as """
Now running `pre-commit run --all-files` shouldn't error.
Closes: https://github.com/mozilla-ai/any-agent/issues/261
> Explicitly ignore conflicting rules due to `extend-select = ["ALL"]`

- docs/frameworks/smolagents.md
CodeAgent seems to be not used. Fixing the docs.
> Fix docs: default agent in smolagents is ToolCallingAgent

- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- .github/workflows/tests.yaml
- CONTRIBUTING.md
- pyproject.toml
This PR adds `[dependency-groups]` to the `pyproject.toml`, so tools like [`uv`](https://docs.astral.sh/uv/) can correctly install development dependencies when you run (for example):
```console
uv sync --group dev --extra all
```
See: https://peps.python.org/pep-0735/
See: https://packaging.python.org/en/latest/specifications/dependency-groups/
For some reason `pip` is not compatible with dependency groups despite the above and PEP0735. `dev` is a dependency group so this command doesn't install the `dev` group, just the 'all' optional extras:
```console
pip install -e ".[dev,all]"
```
You get a warning that there's no 'optional' (extra) group named `dev`:
```console
WARNING: any-agent 0.14.2.dev3+gbd66881 does not provide the extra 'dev'
```
> Add `[dependency-groups]` in `pyproject.toml`

- .github/workflows/tests.yaml
- pyproject.toml
- Updated `pyproject.toml` to include `pytest-xdist` as a testing dependency.
- Modified GitHub Actions workflow to run integration tests in parallel using `-n auto` for improved efficiency.
> chore(tests): Add pytest-xdist for parallel test execution

- .github/workflows/tests.yaml
- docs/evaluation.md
PR https://github.com/mozilla-ai/any-agent/pull/307 removed duplicate code, but that duplicate code was what was making the docs python code tester run correctly. But, the github action test wasn't triggered because it doesn't run when the docs change.
> Test when docs change, and fix broken docs

- pyproject.toml
Pydantic v2.11.5 broke our code: https://github.com/pydantic/pydantic/releases/tag/v2.11.5 
```
return self.validator.validate_python(
object,
strict=strict,
from_attributes=from_attributes,
context=context,
allow_partial=experimental_allow_partial,
by_alias=by_alias,
by_name=by_name,
)
E       pydantic_core._pydantic_core.ValidationError: 33 validation errors for union[AgnoMCPServerStdio,AgnoMCPServerSse,GoogleMCPServerStdio,GoogleMCPServerSse,LangchainMCPServerStdio,LangchainMCPServerSse,LlamaIndexMCPServerStdio,LlamaIndexMCPServerSse,OpenAIMCPServerStdio,OpenAIMCPServerSse,SmolagentsMCPServerStdio,SmolagentsMCPServerSse,TinyAgentMCPServerStdio,TinyAgentMCPServerSse]
E       AgnoMCPServerStdio.framework
E         Input should be <AgentFramework.AGNO: 'agno'> [type=literal_error, …
```
> Pin Pydantic

- .github/workflows/tests.yaml
Unfortunately the logic I added in https://github.com/mozilla-ai/any-agent/pull/312 to check whether just docs have changed means that manually triggering the workflow doesn't run all the tests :( 
Until we work on a better mechanism, better to run all tests when there have been changes to docs.
> Run all tests even if only docs changed

- src/any_agent/tools/__init__.py
- src/any_agent/tools/mcp/__init__.py
- src/any_agent/tools/mcp/frameworks/__init__.py
Enhance MCP server initialization with dynamic handling for various agent frameworks
- Introduced `_get_stdio_mcp_server` and `_get_sse_mcp_server` functions to streamline MCP server creation based on the agent framework.
- Updated `_get_mcp_server` to utilize the new functions for better organization and clarity.
- Added support for additional agent frameworks in the MCP server initialization process.
> feat(mcp): Remove TypeAdapter

- pyproject.toml
- src/any_agent/evaluation/evaluate.py
- src/any_agent/evaluation/evaluators.py
- tests/unit/evaluation/test_evaluate.py
- Removed the `evaluate` dependency from `pyproject.toml`.
- Renamed `evaluate_qa_squad` to `evaluate_final_output` for clarity and updated its implementation to use F1 scoring for evaluation.
- Adjusted tests to reflect the new evaluation function name.
This change enhances the evaluation process by providing a more robust scoring mechanism while keeping the code clean and maintainable!
> Remove dependency on hf `evaluate` library

- src/any_agent/tools/a2a.py
The default timeout for the httpx client is criminally low lol. We need to be able to pipe this through so that I can bump up the timeout to something reasonable based on what the agent has to do.
This update introduces an optional `http_kwargs` parameter to the `a2a_tool` function, allowing users to pass additional HTTP client options. This enhancement improves flexibility when making requests to A2A agents. Documentation has been updated accordingly.
> feat(a2a): Add optional http_kwargs parameter

- docs/api/config.md
- docs/cookbook/a2a_as_tool.ipynb
- docs/cookbook/serve_a2a.ipynb
- docs/serving.md
- src/any_agent/config.py
- src/any_agent/frameworks/any_agent.py
- src/any_agent/serving/__init__.py
- src/any_agent/serving/agent_card.py
- src/any_agent/serving/config.py
- src/any_agent/serving/server.py
- tests/integration/test_load_and_run_multi_agent_a2a_tool.py
- tests/integration/test_serve_agent.py
- tests/unit/serving/test_agent_card.py
- tests/unit/tools/test_a2a.py
Now the skills are configurable and I also tweak the API so that it clears the path to allow for future integration of other serving methods like Serving over MCP or ACP.
A2AServingConfig now has an a2a specific type called "AgentSkill" which is no longer appropriate to exist in the main ServingConfig class. This is why I made a new config and put it inside of the `serving` module.
Other than the re-org, the actual code change is in the _get_agent_card function. I also created a unit test.
> 408 A2A agentskills should be configurable

- pyproject.toml
- src/any_agent/tools/mcp/frameworks/llama_index.py
Similar issue we had with Agno a while back. The internal code expects `None` instead of empty list:
https://github.com/run-llama/llama_index/blob/98739a603768e37a98c70275113d98e5d1f0979e/llama-index-integrations/tools/llama-index-tools-mcp/llama_index/tools/mcp/base.py#L95-L97
> fix(llama_index): Don't set `allowed_tools` to empty list.

- src/any_agent/frameworks/google.py
- src/any_agent/tools/final_output.py
- tests/unit/tools/mcp/test_unit_openai_mcp.py
Two things here: one fix, and one "infinite loop til max steps" fix.
The problem: Google wasn't getting the hint that the problem wasn't with the info provided, but the fact that it was providing a direct string and not a json string. 
The fix: Use a two stage validation approach. Step one, make sure they passed a valid json string, if not, return an error saying that it's invalid JSON. Step two, once it's valid JSON, then we can try to parse it with pydantic.
Now:
> feat(agent): Enhance final output handling with retry logic and JSON validation

- src/any_agent/tracing/instrumentation/llama_index.py
The new llama-index-core version 0.12.44 seems to add a typevar to Context. This PR aligns the instrumenter with this change to avoid type checking issues.
> Add missing typevar in LlamaIndex

- src/any_agent/serving/server_mcp.py
Apparently, the bump of `mcp` to 1.10.0 now causes one of the type ignore annotations to become unnecessary, breaking the lint. This PR removes the unused type ignore annotation.
> Remove unused type ignore

- pyproject.toml
- src/any_agent/serving/server_mcp.py
Reverts mozilla-ai/any-agent#533 because MCP patched the bug fast! 🎉
> Revert "Pin MCP"

- pyproject.toml
- src/any_agent/tools/mcp/frameworks/openai.py
Workaround OpenAI breaking change until https://github.com/openai/openai-agents-python/issues/976 .
the Agent / Run Ctx is only used if using the built in "filtering" of MCP in the OpenAI Agents framework, so the dummy agent/ctx I make here is never used.
> Fix OpenAI breaking change

- src/any_agent/frameworks/llama_index.py
This pull request introduces enhancements to the `llama_index` framework by integrating the `litellm` library to enforce structured outputs when specified, ensuring better compatibility with user-defined schemas.
> feat: more stable structured outputs in llama_index

- src/any_agent/tools/a2a.py
- tests/integration/a2a/test_a2a_serve.py
- tests/integration/a2a/test_a2a_tool.py
- tests/integration/a2a/test_a2a_tool_multiturn.py
Default httpx timeout is 5 seconds. Occasionally an agent takes longer than 5 seconds, so imo it's an unreasonable default for our use case.
This should help stabilize our integration tests too
> Increase timeout for message sending in integration tests 🕒✨

- pyproject.toml
- src/any_agent/serving/a2a/agent_executor.py
The `typing.override` decorator is not available in python 3.11. A noop decorator is provided instead for that version.
Closes #565
> Avoid import errors in Python 3.11

- src/any_agent/frameworks/tinyagent.py
- tests/unit/frameworks/test_tinyagent.py
Each time run_async is called, it shouldn't inherit any changes made by other run_async calls.
> fix: isolate completion_params

- README.md
- docs/agents/index.md
- docs/agents/tools.md
Consolidate into a single section that share the same use case and can be linked.
> docs: Reorder Agents-As-Tools 

- pyproject.toml
As discussed via slack: The Google A2A Python SDK and API is still in development and has put breaking changes into patch versions a few times. I'd like to switch over to pin the a2a version and use dependabot to carefully manged the version range until the a2a sdk gets more stable.
> feat: pin a2a sdk version

- src/any_agent/serving/a2a/envelope.py
Found while working on Mistral:
I noticed that sometimes a model served over A2A would respond with setting TaskStates to one of the task states that we don't support in non-streaming mode, like TaskState.working or TaskState.submitted, which are meaningless in a non-streaming scenario. To this end, I propose restricting to either 'completed ✅ ' 'input_required❓ ' or 'failed ❌ ' since these are the only ones we'd leverage with our implementation.
> feat: restrict taskstates to those that are used.

- scripts/hooks.py
Tested locally with `mkdocs build` and manually checking the generated `site`:
> fix(hooks): Add `any-agent` to `BASE_URL`.

- src/any_agent/frameworks/smolagents.py
Re: https://github.com/mozilla-ai/any-agent/issues/662 - I do not envision a case where we would want to remove `final_answer` from smolagent tools unless we provide an output type, so I took the liberty of suggesting this patch.
I tested this locally and worked as expected (i.e. now the agent terminates correctly) but I am not 100% sure it will not have other consequences I might have missed (let's see how the tests do in the meantime... :-) ).
Closes https://github.com/mozilla-ai/any-agent/issues/662
> Removed deletion of final_answer when output_type is not defined

- src/any_agent/tools/a2a.py
The cause of the failures was the agent deciding to pass `"'0"` as task_id instead of `None`.
Integration tests:
https://github.com/mozilla-ai/any-agent/actions/runs/16721786710/job/47327664062
> fix(a2a): Make instructions of `_send_query` more clear.

- .github/workflows/tests-cookbook.yaml
- tests/cookbooks/test_cookbooks.py
The previous github artifacts were only containing the original notebooks, so they were not useful at all for debugging. 
After this PR, the artifacts contain the executed notebook output so it can be inspected.
> tests(cookbooks): Save executed notebooks to github cache for debugging.

- README.md
Update the image logo in the README to use an absolute URL pointing to the raw GitHub content. This change ensures that the image is displayed correctly on external sites that render the README, such as PyPI.
> Use absolute URL for logo in README

- pyproject.toml
- src/any_agent/frameworks/tinyagent.py
- src/any_agent/utils/cast.py
- tests/unit/utils/test_cast.py
Added a safe casting function to handle argument types, including union types.
Found when working in any-forge, We had some bool | None types that were silently being ignored
> Implement safe argument casting in tinyagent.py
